name: PRCleanup

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      run_signatures_cleanup:
        description: 'Run signature cleanup'
        required: false
        default: 'false'

jobs:
  cleanup_helm:
    runs-on: ubuntu-latest
    env:
      TRAINING_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
      TRAINING_NAMESPACE: 'pitc-cicd-dagger-techlab-test'
      KUBE_CONFIG_PATH: '$HOME/.kube'
      KUBE_CONFIG_FILENAME: 'config'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
          
      - name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST_AV2 }}'
        run: bash ./scripts/create_kubeconfig.sh
      - name: Remove PR Environment Helm Release
        run: bash ./scripts/remove_helm_release.sh

  cleanup_registry:
    runs-on: ubuntu-latest
    needs: cleanup_helm
    env:
      ORG: '${{ github.repository_owner }}'
      PACKAGE_NAME: '${{ github.event.repository.name }}'
      PACKAGE_TYPE: 'container'
      TAG: "pr-${{ github.event.pull_request.number }}"
      LOGIN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false
          fetch-depth: 0
      - name: Run registry cleanup script
        run: bash ./scripts/cleanup_registry.sh

  cleanup_signatures:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_signatures_cleanup == 'true' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: cleanup_registry
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Cleanup Non-Latest Signatures
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Fetching package versions..."
          gh api -H "Accept: application/vnd.github+json" \
            /user/packages/container/${REPO##*/}/versions \
            -q '.[] | select(.metadata.container.tags | index("latest") | not) | .id' |
          while read -r version_id; do
            echo "Deleting version ID $version_id (non-latest)..."
            gh api --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /user/packages/container/${REPO##*/}/versions/"$version_id"
          done
