name: PRCleanup

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  cleanup_helm:
    runs-on: ubuntu-latest
    env:
      TRAINING_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
      TRAINING_NAMESPACE: 'pitc-cicd-dagger-techlab-test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'
      - name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST_AV2 }}'
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
      - name: Remove PR Environment Helm Release
        env:
          TRAINING_HELM_RELEASE: ${{ env.TRAINING_HELM_RELEASE }}
          TRAINING_NAMESPACE: ${{ env.TRAINING_NAMESPACE }}
          KUBECONFIG: $HOME/.kube/config
        run: bash ./scripts/remove_helm_release.sh

  cleanup_registry:
    runs-on: ubuntu-latest
    env:
      ORG: '${{ github.repository_owner }}'
      PACKAGE_NAME: '${{ github.event.repository.name }}'
      PACKAGE_TYPE: 'container'
      TAG: "pr-${{ github.event.pull_request.number }}"
      LOGIN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Run registry cleanup script
        run: bash ./scripts/cleanup_registry.sh
