name: PRCleanup

on:
  workflow_dispatch:
    inputs:
      only_signatures:
        description: 'Only run signature cleanup?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  cleanup_helm:
    if: ${{ github.event.inputs.only_signatures == 'false' }}
    runs-on: ubuntu-latest
    env:
      TRAINING_HELM_RELEASE: 'pr-${{ github.event.pull_request.number }}'
      TRAINING_NAMESPACE: 'pitc-cicd-dagger-techlab-test'
      KUBE_CONFIG_PATH: '$HOME/.kube'
      KUBE_CONFIG_FILENAME: 'config'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
          
      - name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST_AV2 }}'
        run: bash ./scripts/create_kubeconfig.sh
      - name: Remove PR Environment Helm Release
        run: bash ./scripts/remove_helm_release.sh

  cleanup_registry:
    if: ${{ github.event.inputs.only_signatures == 'false' }}
    runs-on: ubuntu-latest
    needs: cleanup_helm
    env:
      ORG: '${{ github.repository_owner }}'
      PACKAGE_NAME: '${{ github.event.repository.name }}'
      PACKAGE_TYPE: 'container'
      TAG: "pr-${{ github.event.pull_request.number }}"
      LOGIN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false
          fetch-depth: 0
      - name: Run registry cleanup script
        run: bash ./scripts/cleanup_registry.sh

  list_all_packages:
    if: ${{ github.event.inputs.only_signatures == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: List all packages for this repository
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          OWNER="${REPO%%/*}"
          NAME="${REPO##*/}"

          echo "Fetching all packages for ${OWNER}/${NAME}..."

          gh api -H "Accept: application/vnd.github+json" \
            /orgs/${OWNER}/packages?package_type=container |
          jq -r '.[] | [.name, .package_type, .html_url] | @tsv'
