name: Test

permissions:
  contents: read
  packages: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD_VERSION: ${{ github.ref == 'refs/heads/main' && 'latest' || format('pr-{0}', github.event.pull_request.number) }}
  HELM_RELEASE: ${BUILD_VERSION}
  HELM_NAME: dagger-techlab-puzzle
  NAMESPACE: pitc-cicd-dagger-techlab-test
  TRAINING_VERSION: ${{ github.sha }}
  PR_ENV_URL: https://dagger-techlab-pr-${{ github.event.pull_request.number }}.ocp.cloudscale.puzzle.ch
  MY_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || format('pr-{0}', github.event.pull_request.number) }}
  MY_ENV_SEC_VAR: ${{ ${BUILD_VERSION} == 'latest' && 'KUBECONFIG_PROD_CRA' || 'KUBECONFIG_TEST_CRA' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Env
        run: env | sort
      - name: File
        run: echo ${MY_ENV_SEC_VAR}
      - name: File2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[env.MY_ENV_SEC_VAR] }}
        run: |
          printenv | grep AWS_